name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          submodules: true
          # we need full git history for article dates
          fetch-depth: 0
          
    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.5
        
    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install
      # at some point all npm needs to be in package.json
      run: |
        npm install
        npm install -g less@2.7
        npm install -g less-plugin-clean-css@1.5
        haxelib install CodeCookBook-neko.hxml --always --quiet
        haxelib install highlighting.hxml --always --quiet
        haxelib list

    - name: Run build script
      run: haxe build.hxml

    - name: Upload build artifacts (optional)
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          output/
          output/
        if-no-files-found: ignore
